//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SleekBill.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int clientid { get; set; }
        public string client_name { get; set; }
        public string contact_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string gstin { get; set; }
        public string tin { get; set; }
        public string pan { get; set; }
        public string vatno { get; set; }
        public string billing_address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string pincode { get; set; }
        public string country { get; set; }
        public string private_client_details { get; set; }
        public string other_client_details { get; set; }
        public string alt_shipping_address { get; set; }
        public string alt_city { get; set; }
        public string alt_state { get; set; }
        public string alt_pincode { get; set; }
        public string alt_country { get; set; }
    }
}
