//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SleekBill.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int invoiceid { get; set; }
        public string client { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public Nullable<int> purchaseordernumber { get; set; }
        public string paymentterms { get; set; }
        public Nullable<System.DateTime> purchaseorderdate { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public string placeofsupply { get; set; }
        public string product { get; set; }
        public string description { get; set; }
        public string uom { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> unitprice { get; set; }
        public Nullable<decimal> discount { get; set; }
        public string tax { get; set; }
        public string paymenttype { get; set; }
        public Nullable<decimal> amountpaid { get; set; }
        public string notes { get; set; }
        public string noteforclient { get; set; }
        public string privatenote { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
